### ISSUE TITLE
Failed to compile with the Rust toolchain 1.80

### ISSUE THREAD

**Issue by YuanYuYuan** [ZettaScaleLabs/rmw_zenoh#5]
## Error

```bash
error[E0282]: type annotations needed for `Box<_>`
  --> /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.28/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
help: consider giving `items` an explicit type, where the placeholders `_` are specified
   |
83 |     let items: Box<_> = format_items
   |              ++++++++

For more information about this error, try `rustc --explain E0282`.
```

## Fix to merge

https://github.com/eclipse-zenoh/zenoh/pull/1273

## Linked issues

https://github.com/eclipse-zenoh/zenoh-c/issues/557

**Comment by YuanYuYuan** [comment]
Closed by https://github.com/eclipse-zenoh/zenoh-c/pull/560
